### ISSUE TITLE
unable to recover polygon

### ISSUE THREAD

**Issue by alice2108** [Mambix/co2tools#11]
执行co2tools solidify 报错

**Comment by Mambix** [comment]
english please :)

**Comment by Mambix** [comment]
@alice2108 and a sample file that demonstrates the crash so I can debug it and fix it

**Comment by alice2108** [comment]
> s
![image](https://user-images.githubusercontent.com/38448057/132079428-61048829-3332-483f-8b13-f1a3bce00060.png)
![image](https://user-images.githubusercontent.com/38448057/132079434-533b7a57-9900-490a-86dc-7cbb09d66cc9.png)


[5.25.zip](https://github.com/Mambix/co2tools/files/7109083/5.25.zip)

**Comment by Mambix** [comment]
@alice2108 what layers are you trying to extrude?
I don't know if you specify that in you yml file (maybe you could post your definition too) or not.
But when not changed objects from `CUT` layer will be extruded together from `HOLES` and `HOLES_PLEXI`, then the holes layers will be cut from CUT object.

Another thing to note is that this library was never intended to extrude multiple objects. It was designed so you extrude and cut single object to check 3D fit. Imagine you want to cut 6 sides of a cube. In that case you would have 6 dxf files (one for each side) that you would extrude and then check if the cuts fit together in some 3D program like FreeCAD for example.
